'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import allProjects from '@/data/projects.json';
type Project=typeof allProjects[number];
function Lightbox({items,start,onClose}:{items:Project[];start:number;onClose:()=>void}){const [index,setIndex]=useState(start);const dialog=useRef<HTMLDialogElement>(null);const touch=useRef<number|null>(null);const p=items[index];
 useEffect(()=>{const el=dialog.current;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;el?.showModal();document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow=overflow;previous?.focus()}},[]);
 const move=(n:number)=>setIndex(i=>(i+n+items.length)%items.length);
 return <dialog ref={dialog} className="lightbox" aria-label="Project photograph viewer" onCancel={e=>{e.preventDefault();onClose()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="lightbox-top"><span>CARREIRO / OUR WORK</span><button autoFocus onClick={onClose} aria-label="Close photograph">Close <span aria-hidden="true">×</span></button></div><div className="lightbox-stage" onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current===null)return;const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta<0?1:-1);touch.current=null}}><button className="lightbox-prev" onClick={()=>move(-1)} aria-label="Previous photograph">←</button><Image key={p.id} src={p.src} alt={p.alt} width={p.width} height={p.height} sizes="100vw" className="lightbox-photo"/><button className="lightbox-next" onClick={()=>move(1)} aria-label="Next photograph">→</button></div><div className="lightbox-bottom" aria-live="polite"><p>{p.alt}</p><span>{index+1} / {items.length}</span></div></dialog>
}
export function Gallery({featured=false}:{featured?:boolean}){const [filter,setFilter]=useState('All');const [active,setActive]=useState<number|null>(null);const items=featured?[44,77,75,137].map(id=>allProjects.find(p=>p.id===id)!):allProjects.filter(p=>filter==='All'||p.category===filter||(filter==='In progress'&&p.stage==='In progress'));
 return <>{!featured&&<div className="gallery-toolbar"><div className="filters" aria-label="Filter project photographs">{['All','Hardwood','Vinyl','Laminate','Stairs','In progress'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><span className="image-count" aria-live="polite">{items.length} photographs</span></div>}{!featured&&<p className="gallery-note">Real projects, from installation details to finished spaces. Materials are labeled only when identifiable.</p>}<div className={featured?'featured-grid':'gallery-grid'} key={filter}>{items.map((p,i)=><figure key={p.id} className="project-card"><button onClick={()=>setActive(i)} aria-label={`View photograph: ${p.alt}`}><Image src={featured?p.src:p.thumb} alt={p.alt} width={p.width} height={p.height} sizes={featured?'(max-width: 700px) 100vw, 50vw':'(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw'} unoptimized={!featured} loading="lazy" onError={e=>{e.currentTarget.style.opacity='0';e.currentTarget.parentElement?.classList.add('image-unavailable')}}/><span className="image-open" aria-hidden="true">↗</span></button><figcaption><span>{p.category==='Uncategorized'?'Flooring detail':p.category}</span><span>{p.stage==='In progress'?'In progress': 'View photograph ↗'}</span></figcaption></figure>)}</div>{active!==null&&<Lightbox items={items} start={active} onClose={()=>setActive(null)}/>}</>
}
