'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {navigation} from '@/lib/business';
export function Navigation(){const path=usePathname();const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const panel=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}if(e.key==='Tab'){const els=[toggle.current,...Array.from(panel.current?.querySelectorAll<HTMLAnchorElement>('a')||[])].filter(Boolean) as HTMLElement[];const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[open]);
 return <header className="site-header"><div className="nav-inner"><Link href="/" className="wordmark" aria-label="Carreiro Flooring Contractor LLC home" onClick={()=>setOpen(false)}><span className="brand-symbol" aria-hidden="true">C<span>F</span></span><span>CARREIRO<small>FLOORING CONTRACTOR LLC</small></span></Link><nav aria-label="Main navigation" className="desktop-nav">{navigation.map(n=><Link key={n.href} href={n.href} aria-current={path===n.href?'page':undefined}>{n.label}</Link>)}</nav><Link className="nav-quote" href="/contact">Get a quote <span aria-hidden="true">↗</span></Link><button className="menu-toggle" ref={toggle} onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Close menu':'Open menu'}><span/ ><span/></button></div><nav ref={panel} id="mobile-menu" aria-label="Mobile navigation" className={`mobile-nav ${open?'is-open':''}`} inert={!open}>{navigation.map((n,i)=><Link key={n.href} href={n.href} onClick={()=>setOpen(false)} aria-current={path===n.href?'page':undefined}><small>0{i+1}</small>{n.label}<span aria-hidden="true">↗</span></Link>)}<Link className="button" href="/contact" onClick={()=>setOpen(false)}>Get a free quote ↗</Link></nav></header>
}
