import Link from 'next/link';
import {Button,CTA,ProjectImage,Arrow} from '@/components/ui';
import {Gallery} from '@/components/gallery';
import {services} from '@/data/services';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('Professional Flooring Installation','Hardwood, vinyl, laminate and stairs by Carreiro Flooring Contractor LLC. Discover real flooring projects and request your free quote.','/');
export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="little-line"/> Thoughtfully installed. Beautifully lived in.</p><h1>A beautiful home<br/>starts from<br/><em>the floor up.</em></h1><p className="hero-description">Hardwood, vinyl, laminate and stairs.<br/>Professional flooring that brings your<br className="desktop-break"/> space together, one detail at a time.</p><div className="hero-actions"><Button/><Link className="text-link" href="/gallery">View our work <Arrow/></Link></div><div className="hero-foot"><span>CARREIRO FLOORING CONTRACTOR LLC</span><a href="#introduction" aria-label="Explore the website">Explore ↓</a></div></div><div className="hero-photo"><ProjectImage id={44} priority sizes="(max-width: 800px) 100vw, 52vw"/><div className="hero-caption"><span>Real spaces. Our work.</span><span>01 / Flooring portfolio</span></div></div></section>
 <div className="service-ribbon" aria-label="Our flooring specialties">{services.map(s=><Link href={'/services#'+s.id} key={s.id}>{s.name}<span aria-hidden="true">↗</span></Link>)}</div>
 <section id="introduction" className="container intro-section"><p className="eyebrow">A foundation for better living</p><div><h2>More than a surface.<br/><em>The feeling of home.</em></h2><div className="intro-bottom"><p>Flooring sets the tone for every room. At Carreiro Flooring Contractor LLC, our focus is professional installation, thoughtful details and a clean, cohesive finish.</p><Link href="/about" className="text-link">Meet Carreiro <Arrow/></Link></div></div></section>
 <section className="section service-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Our expertise</p><h2>Four ways to<br/><em>transform your space.</em></h2></div><Link className="text-link" href="/services">Explore our services <Arrow/></Link></div><div className="service-cards">{services.map((s,i)=><Link key={s.id} href={'/services#'+s.id} className="service-card"><div className="service-photo"><ProjectImage id={s.image} sizes="(max-width: 600px) 90vw, (max-width: 1000px) 45vw, 25vw"/><span className="service-number">0{i+1}</span></div><h3>{s.name}<Arrow/></h3><p>{s.short}</p></Link>)}</div></div></section>
 <section className="container section"><div className="section-heading"><div><p className="eyebrow">The work speaks for itself</p><h2>Our recent work.</h2></div><Link className="text-link" href="/gallery">View full gallery <Arrow/></Link></div><Gallery featured/></section>
 <section className="care-section"><div className="container care-grid"><div><p className="eyebrow">The details make the difference</p><h2>Care in the work.<br/><em>Character in the result.</em></h2><p>From the material you choose to the way one room meets the next, good flooring is a collection of carefully considered details.</p><Button>Let’s talk about your project</Button></div><div className="principles">{[['Attention to detail','Edges, transitions and layout all contribute to a considered finished appearance.'],['Professional installation','A flooring project brings together preparation, material selection and careful installation.'],['A cohesive home','Hardwood, vinyl, laminate and stair finishes offer different ways to connect your spaces.']].map(([title,copy],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section><CTA/>
 </>}
